# coding: utf-8
# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.0.post6+g7c87f5a.d20221028'
__version_tuple__ = version_tuple = (0, 0, 'g7c87f5a.d20221028')
