<script setup lang="ts">
import {useSamplesStore} from "@/stores/samples";
const samples = useSamplesStore();
</script>

<template>
  <div>
    <h1>Admin page</h1>
    <p>This is a temporary view of the data generated by the user</p>
    <p>In the real website this data will be stored in a database</p>
    <h3>Samples requested this week:</h3>
    <ul>
    <li v-for="sample in samples.samples">
      {{sample["name"]}}
    </li>
    </ul>
  </div>
</template>